const catchAsync = require('../utils/catchAsync')
const AppError = require('../utils/appError')
const factory = require('./handlerFactory')
const Lecture = require('../Models/Courses/LectureModel')
const MCQ = require('../Models/Exams/MCQModel')
const MEQ = require('../Models/Exams/MEQModel')
const LectureQuiz = require('../Models/Exams/LectureQuizModel')
const MCQAnswer = require('../Models/Exams/Answers/MCQAnswerModel')

exports.createMcq = factory.createOne(MCQ)
exports.getAllMcq = factory.getAll(MCQ)
exports.createQuiz = factory.createOne(LectureQuiz)
exports.getAllQuizzes = factory.getAll(LectureQuiz)
exports.createMeq = factory.createOne(MEQ)
exports.getAllMeq = factory.getAll(MEQ)
