const catchAsync = require('../utils/catchAsync')
const AppError = require('../utils/appError')
const factory = require('./handlerFactory')
const Student = require('../Models/Users/StudentModel')

exports.createStudent = factory.createOne(Student)
exports.getAllStudents = factory.getAll(Student)
exports.getOneStudent = factory.getOne(Student)
exports.updateStudent = factory.getOne(Student)
exports.deleteStudent = factory.deleteOne(Student)
